codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        informational: true

ignore:
  - "cmd"
  - "prometheus_interface"